#include "stdafx.h"
#include "Levels.h"
#include "Levels/Level1.h"
#include "Levels/Level2.h"
#include "Levels/Level3.h"
#include "Levels/Level4.h"
#include "Levels/Level5.h"
#include "Levels/Level6.h"
#include "Levels/Level7.h"
#include "Levels/Level8.h"
#include "Levels/Level9.h"
#include "Levels/Level10.h"
#include "Levels/Level11.h"
#include "Levels/Level12.h"
#include "Levels/Level13.h"
#include "Levels/Level14.h"
#include "Levels/Level15.h"
#include "Levels/Level16.h"
#include "Levels/Level17.h"
#include "Levels/Level18.h"
#include "Levels/Level19.h"
#include "Levels/Level20.h"
#include "Levels/Level21.h"

BaseLevel* Levels::createLevel(int level)
{
	switch(level){
	case 1:
		return Level1::create();
	case 2:
		return Level2::create();
	case 3:
		return Level3::create();
	case 4:
		return Level4::create();
	case 5:
		return Level5::create();
	case 6:
		return Level6::create();
	case 7:
		return Level7::create();
	case 8:
		return Level8::create();
	case 9:
		return Level9::create();
	case 10:
		return Level10::create();
	case 11:
		return Level11::create();
	case 12:
		return Level12::create();
	case 13:
		return Level13::create();
	case 14:
		return Level14::create();
	case 15:
		return Level15::create();
	case 16:
		return Level16::create();
	case 17:
		return Level17::create();
	case 18:
		return Level18::create();
	case 19:
		return Level19::create();
	case 20:
		return Level20::create();
	case 21:
		return Level21::create();
	}
	return nullptr;
}
