#include "stdafx.h"
#include "Levels.h"
#include "Level1.h"
#include "Level2.h"
#include "Level3.h"
#include "Level4.h"
#include "Level5.h"
#include "Level6.h"
#include "Level7.h"
#include "Level8.h"
#include "Level9.h"
#include "Level10.h"
#include "Level11.h"
#include "Level12.h"
#include "Level13.h"
#include "Level14.h"
#include "Level15.h"
#include "Level16.h"
#include "Level17.h"
#include "Level18.h"
#include "Level19.h"
#include "Level20.h"
#include "Level21.h"
#include "Level22.h"
#include "Level23.h"
#include "Level24.h"

BaseLevel* Levels::createLevel(int level)
{
	switch(level){
	case 1:
		return Level1::create();
	case 2:
		return Level2::create();
	case 3:
		return Level3::create();
	case 4:
		return Level4::create();
	case 5:
		return Level5::create();
	case 6:
		return Level6::create();
	case 7:
		return Level7::create();
	case 8:
		return Level8::create();
	case 9:
		return Level9::create();
	case 10:
		return Level10::create();
	case 11:
		return Level11::create();
	case 12:
		return Level12::create();
	case 13:
		return Level13::create();
	case 14:
		return Level14::create();
	case 15:
		return Level15::create();
	case 16:
		return Level16::create();
	case 17:
		return Level17::create();
	case 18:
		return Level18::create();
	case 19:
		return Level19::create();
	case 20:
		return Level20::create();
	case 21:
		return Level21::create();
	case 22:
		return Level22::create();
	case 23:
		return Level23::create();
	case 24:
		return Level24::create();
	}
	return nullptr;
}
